
name: My First workflow at GitHub Actions

on:
  push:
    branches: [ "main" ]
    
jobs:
  job01:
        name: Executando o job01
        runs-on: self-hosted
        steps:
          - name: Step 1 
            uses: actions/checkout@v2
        
          - name: Step 2
            run: echo Hello, world!
